# Generated by Django 3.2.9 on 2021-11-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='details',
            name='lastname',
        ),
    ]
