# Generated by Django 3.2.9 on 2021-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211125_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('registered', 'registered'), ('unregistered', 'unregistered')], default='registered', max_length=50),
        ),
    ]
