# Generated by Django 3.2.9 on 2021-11-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_month', models.CharField(max_length=10)),
                ('date_day', models.CharField(max_length=2)),
                ('date_weekday', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('registered', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('performers', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
