# Generated by Django 3.2.9 on 2021-11-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsstory',
            name='date_day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eventsstory',
            name='date_month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventsstory',
            name='date_weekday',
            field=models.CharField(max_length=50),
        ),
    ]
