# Generated by Django 3.2.9 on 2021-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsstory',
            name='comment',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
