# Generated by Django 3.2.9 on 2021-12-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211201_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsstory',
            name='url',
            field=models.CharField(default=70, max_length=500),
            preserve_default=False,
        ),
    ]
